Feature/info page frontend
NoNamer777/WA-2022-group-2 pull request #25
Opened 2023-05-19 19:44 UTC by JGoudswaard

Pull request voor de info pagina. 
Excuses voor hoe lang het duurde.

2023-05-20 13:50 UTC, NoNamer777 requested changes
Could you run prettier (`format:write`) so that the linting errors are solved? It's a bit hard to review atm

2023-05-20 14:04 UTC, majsa1 requested changes
Looks good! 
Pls see comments

2023-05-20 14:04 UTC, majsa1 commented on packages/client/src/app/views/InfoView.vue
> +          Welkom op de website! <br />
Please check the responsiveness, some texts overlap. You may need to rearrange flex boxes and/or use flex-wrap

2023-05-22 11:48 UTC, ahmed-ben10 requested changes

2023-05-22 11:48 UTC, ahmed-ben10 commented on packages/client/src/app/views/InfoView.vue
> +<script setup></script>
remove the script tag if it's not used

2023-05-23 08:57 UTC, NoNamer777 commented on packages/client/src/app/views/InfoView.vue
> +};
Is there a reason why you've put the texts for the `main`, `footer`, and `register` inside a Js object instead of directly putting them in the HTML?

2023-05-23 19:27 UTC, NoNamer777 approved these changes
LGTM

2023-05-24 19:28 UTC, NoNamer777 submitted a review, later dismissed
LGTM

2023-05-24 20:04 UTC, ahmed-ben10 approved these changes

2023-05-24 20:31 UTC, ahmed-ben10 requested changes

2023-05-24 20:31 UTC, ahmed-ben10 commented on packages/client/src/app/views/InfoView.vue
> +      <router-link v-if="!isAuthenticated" class="btn btn-primary" :to="{ name: 'register' }"
Can you split this in 3 lines:

<router-link v-if="!isAuthenticated" class="btn btn-primary" :to="{ name: 'register' }">
  Registreer
</router-link >

2023-05-24 20:31 UTC, ahmed-ben10 commented on packages/client/src/app/views/InfoView.vue
> +      <router-link v-if="!isAuthenticated" class="btn btn-primary" :to="{ name: 'register' }"
<router-link v-if="!isAuthenticated" class="btn btn-primary" :to="{ name: 'register' }">
  Registreer
</router-link >

2023-05-24 20:56 UTC, ahmed-ben10 approved these changes
Good job!

2023-05-25 10:27 UTC, NoNamer777 approved these changes

2023-05-25 15:18 UTC, merged