Boyscout/fix routes
NoNamer777/WA-2022-group-2 pull request #5
Opened 2023-04-25 14:29 UTC by NoNamer777

- Move the `assets/*` and the `favicon` into a `src/public` folder so that all static files that are not code related can be imported from one place. When using files from the place (think of images or stylesheets you must import them as follows:

`/assets/<sub-path-to-file...>`

This was done so that the assets are not duplicated, or put directly in the root of the build output folder while making a build.

- Add `index` files into the sub folders for views, components, stores and in the app and src folder. These will help determine which item can be imported from where and help organise and clean up the imports in other files.

2023-04-25 16:24 UTC, ahmed-ben10 requested changes

2023-04-25 16:24 UTC, ahmed-ben10 commented on packages/client/src/app/views/LoginView.vue
> +import Mascot from '../../public/assets/images/mascot/happy_bin_login.png'
Should this import not be removed?

2023-04-25 16:27 UTC, NoNamer777 commented on packages/client/src/app/views/LoginView.vue
> +import Mascot from '../../public/assets/images/mascot/happy_bin_login.png'
Yes, it should. I'll fix that

2023-04-28 18:15 UTC, ahmed-ben10 approved these changes

2023-04-28 18:15 UTC, merged